import java.net.HttpURLConnection
import java.net.URI
import java.net.URLEncoder
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// Bakes real orbital elements for (20137) 1996 PX8 Angeljorba into the app at build time, per
// the design handoff's recommendation: fetch once at build time rather than at wallpaper
// runtime (no INTERNET permission needed, no risk of a broken state if JPL is unreachable).
// Falls back to the last-known catalog orbit (shape/tilt real, position-along-orbit a stand-in)
// if every source fails — this must never break the build. This is a secondary/best-effort
// layer; the app itself (AsteroidOrbitFetcher.kt) fetches and verifies this live on open too,
// with the same source list, and that result takes priority at runtime — see WallpaperPrefs.
val asteroidElementsOutputDir = layout.buildDirectory.dir("generated/asteroidElements/kotlin")

val generateAsteroidElements by tasks.registering {
    val outputDirProvider = asteroidElementsOutputDir
    outputs.dir(outputDirProvider)
    doLast {
        data class Elements(
            val a: Double,
            val e: Double,
            val i: Double,
            val om: Double,
            val w: Double,
            val ma: Double,
            val epoch: Double,
        )

        // Baked-in catalog orbit (a, e, i, om are real JPL values; w/ma were unavailable when
        // this was last hand-written, so position-along-orbit was a stand-in at perihelion).
        val fallback = Elements(
            a = 2.2895838, e = 0.3045701, i = 5.86541, om = 150.65575, w = 0.0, ma = 0.0, epoch = 2461232.5,
        )

        val target = "https://ssd-api.jpl.nasa.gov/sbdb.api?sstr=20137&full-prec=1"
        val encodedTarget = URLEncoder.encode(target, "UTF-8")
        // Same sources (and same order) as AsteroidOrbitFetcher.kt's runtime fetch — direct
        // request first, then a few independent read-only CORS relays as fallbacks, since JPL's
        // API can 403 unrecognized/automated clients even outside a browser's CORS policy.
        val sources = listOf(
            "direct" to target,
            "allorigins relay" to "https://api.allorigins.win/raw?url=$encodedTarget",
            "corsproxy relay" to "https://corsproxy.io/?url=$encodedTarget",
            "codetabs relay" to "https://api.codetabs.com/v1/proxy?quest=$encodedTarget",
            "thingproxy relay" to "https://thingproxy.freeboard.io/fetch/$target",
        )

        fun get(urlStr: String): String {
            val connection = URI(urlStr).toURL().openConnection() as HttpURLConnection
            connection.connectTimeout = 8000
            connection.readTimeout = 8000
            connection.setRequestProperty("Accept", "application/json")
            return try {
                val code = connection.responseCode
                check(code in 200..299) { "HTTP $code" }
                connection.inputStream.bufferedReader().use { it.readText() }
            } finally {
                connection.disconnect()
            }
        }

        fun extractElement(json: String, name: String): Double? =
            Regex("\"name\"\\s*:\\s*\"$name\"[^}]*?\"value\"\\s*:\\s*\"(-?[0-9.eE+-]+)\"")
                .find(json)?.groupValues?.get(1)?.toDoubleOrNull()

        var result = fallback
        var source = "fallback (baked-in catalog orbit; every JPL SBDB source unavailable at build time)"

        for ((label, url) in sources) {
            try {
                val json = get(url)
                val a = extractElement(json, "a")
                val e = extractElement(json, "e")
                val i = extractElement(json, "i")
                val om = extractElement(json, "om")
                val w = extractElement(json, "w")
                val ma = extractElement(json, "ma")
                val epoch = Regex("\"epoch\"\\s*:\\s*\"(-?[0-9.eE+-]+)\"").find(json)?.groupValues?.get(1)?.toDoubleOrNull()

                if (a != null && e != null && i != null && om != null && w != null && ma != null && epoch != null) {
                    result = Elements(a, e, i, om, w, ma, epoch)
                    source = "live JPL Small-Body Database fetch at build time ($label, sstr=20137)"
                    break
                } else {
                    logger.warn("generateAsteroidElements: incomplete response from $label, trying next source")
                }
            } catch (ex: Exception) {
                logger.warn("generateAsteroidElements: $label failed (${ex.message}), trying next source")
            }
        }

        val packageDir = outputDirProvider.get().asFile.resolve("com/philpf/solarsystemwallpaper")
        packageDir.mkdirs()
        packageDir.resolve("AsteroidElements.kt").writeText(
            """
            |package com.philpf.solarsystemwallpaper
            |
            |// Generated by the :app:generateAsteroidElements Gradle task (app/build.gradle.kts) — do not edit by hand.
            |// Source: $source
            |object AsteroidElements {
            |    const val a = ${result.a}
            |    const val e = ${result.e}
            |    const val i = ${result.i}
            |    const val om = ${result.om}
            |    const val w = ${result.w}
            |    const val ma = ${result.ma}
            |    const val epochJd = ${result.epoch}
            |}
            |
            """.trimMargin(),
        )
        logger.lifecycle("generateAsteroidElements: $source")
    }
}

tasks.withType<KotlinCompile>().configureEach {
    dependsOn(generateAsteroidElements)
}

android {
    namespace = "com.philpf.solarsystemwallpaper"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.philpf.solarsystemwallpaper"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }

    sourceSets {
        getByName("main").java.srcDir(asteroidElementsOutputDir)
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
}
