plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// Bakes real orbital elements for (20137) 1996 PX8 Angeljorba into the app at build time, per
// the design handoff's recommendation: fetch once at build time rather than at wallpaper
// runtime (no INTERNET permission needed, no risk of a broken state if JPL is unreachable).
// Falls back to the last-known catalog orbit (shape/tilt real, position-along-orbit a stand-in)
// if the fetch fails for any reason — this must never break the build.
val asteroidElementsOutputDir = layout.buildDirectory.dir("generated/asteroidElements/kotlin")

val generateAsteroidElements by tasks.registering {
    val outputDirProvider = asteroidElementsOutputDir
    outputs.dir(outputDirProvider)
    doLast {
        data class Elements(
            val a: Double,
            val e: Double,
            val i: Double,
            val om: Double,
            val w: Double,
            val ma: Double,
            val epoch: Double,
        )

        // Baked-in catalog orbit (a, e, i, om are real JPL values; w/ma were unavailable when
        // this was last hand-written, so position-along-orbit was a stand-in at perihelion).
        val fallback = Elements(
            a = 2.2895838, e = 0.3045701, i = 5.86541, om = 150.65575, w = 0.0, ma = 0.0, epoch = 2461232.5,
        )

        var result = fallback
        var source = "fallback (baked-in catalog orbit; live JPL fetch unavailable at build time)"

        try {
            val url = java.net.URI("https://ssd-api.jpl.nasa.gov/sbdb.api?sstr=20137&full-prec=1").toURL()
            val connection = url.openConnection() as java.net.HttpURLConnection
            connection.connectTimeout = 8000
            connection.readTimeout = 8000
            connection.setRequestProperty("Accept", "application/json")
            val json = connection.inputStream.bufferedReader().use { it.readText() }
            connection.disconnect()

            fun extractElement(name: String): Double? =
                Regex("\"name\"\\s*:\\s*\"$name\"[^}]*?\"value\"\\s*:\\s*\"(-?[0-9.eE+-]+)\"")
                    .find(json)?.groupValues?.get(1)?.toDoubleOrNull()

            val a = extractElement("a")
            val e = extractElement("e")
            val i = extractElement("i")
            val om = extractElement("om")
            val w = extractElement("w")
            val ma = extractElement("ma")
            val epoch = Regex("\"epoch\"\\s*:\\s*\"(-?[0-9.eE+-]+)\"").find(json)?.groupValues?.get(1)?.toDoubleOrNull()

            if (a != null && e != null && i != null && om != null && w != null && ma != null && epoch != null) {
                result = Elements(a, e, i, om, w, ma, epoch)
                source = "live JPL Small-Body Database fetch at build time (sstr=20137)"
            } else {
                logger.warn("generateAsteroidElements: incomplete JPL SBDB response, using fallback orbit")
            }
        } catch (ex: Exception) {
            logger.warn("generateAsteroidElements: JPL SBDB fetch failed (${ex.message}), using fallback orbit")
        }

        val packageDir = outputDirProvider.get().asFile.resolve("com/philpf/solarsystemwallpaper")
        packageDir.mkdirs()
        packageDir.resolve("AsteroidElements.kt").writeText(
            """
            |package com.philpf.solarsystemwallpaper
            |
            |// Generated by the :app:generateAsteroidElements Gradle task (app/build.gradle.kts) — do not edit by hand.
            |// Source: $source
            |object AsteroidElements {
            |    const val a = ${result.a}
            |    const val e = ${result.e}
            |    const val i = ${result.i}
            |    const val om = ${result.om}
            |    const val w = ${result.w}
            |    const val ma = ${result.ma}
            |    const val epochJd = ${result.epoch}
            |}
            |
            """.trimMargin(),
        )
        logger.lifecycle("generateAsteroidElements: $source")
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(generateAsteroidElements)
}

android {
    namespace = "com.philpf.solarsystemwallpaper"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.philpf.solarsystemwallpaper"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }

    sourceSets {
        getByName("main").java.srcDir(asteroidElementsOutputDir)
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
}
